### ISSUE TITLE
Pluto startup fails: "Uncaught TypeError: Cannot read properties of undefined (reading 'Library')"

### ISSUE THREAD

**Issue by gjm-p** [fonsp/Pluto.jl#2046]
I am using Windows 10, Julia 1.7, Pluto 0.19.1, and Chrome 1000.4896.127.

I have just installed Pluto by doing `add Pluto` at a Julia pkg prompt. When I then do `Pluto.run()`, a browser window opens displaying a Pluto welcome notice, saying "Loading...", and a progress bar at the top of that window starts growing. The progress bar eventually reaches the right-hand side of the window, but the "Loading" notice does not go away. If I click on, say, the "new notebook" link on the welcome page, I get a blank page but no content ever appears in it.

If I point a new browser window at the same URI as the original one launched by `Pluto.run()`, the same thing happens.

In the Javascript console, an error appears immediately on going to that URI:

    Uncaught TypeError: Cannot read properties of undefined (reading 'Library')
        at n (editor.30fdc042.js:1:21495)
        at Object.<anonymous> (editor.30fdc042.js:1:21644)
        at r (editor.30fdc042.js:1:402)
        at Object.<anonymous> (editor.30fdc042.js:1:16652)
        at r (editor.30fdc042.js:1:402)
        at index.1a7d4001.js:1:677

I attempted to capture a video recording using the Windows "Game Bar" as requested, but even though it is only 27 seconds long and shows approximately nothing happening in a single window the file is 33MB in size. I do not have a YouTube account. I am fairly sure that the only further information it provides beyond what I have written above is about timing, so: After pasting the URI into the Chrome URL bar, it takes maybe 0.5s or so before (exactly simultaneously, so far as I can see) the welcome notice appears in the browser window and the "Pluto.jl, by ..." message appears in the Javascript console. After about another 0.1s, the error above appears, I-think-simultaneously with when the title in the browser tab changes from showing the URI to saying "Pluto.jl". Another 0.1s after that, the progress bar starts doing its thing; from this point on, nothing visible happens other than the movement of the progress bar. It moves rapidly (~3 seconds) to maybe 2/3 of the way across the window and then crawls more slowly (~10s) to the right-hand side. Nothing further changes after that.

Looking at where the exception happens in the devtools, it appears to be (after prettyprinting the minified JS) here:

    let e = new window.observablehq.Library;

The thing that is squiggly-underlined is "Library" but I think what this actually means is that `window.observablehq` is undefined.

**What I expected to see**

Pluto welcome screen, actual ability to create or load notebooks, no errors in Javascript console.

**What actually happened**

Pluto welcome screen in "loading" state, immediate error in Javascript console, never emerges from "loading" state, cannot create or load notebooks.

**Comment by gjm-p** [comment]
It looks to me as if (1) `editor.30fdc042.js` is the first Javascript to be pulled in, and (2) neither it nor the welcome page itself contains anything that would cause `window.observablehq` to be set. Is this some sort of Javascript bundling problem?

**Comment by gjm-p** [comment]
(I did check for pre-existing reports! But presumably 2045 was submitted between when I started writing mine and when I finished :-).)

I confirm that the problem does indeed appear to be fixed for me with 0.19.2. Thanks!
