### ISSUE TITLE
Can't have Pluto and Jupyter notebooks open at the same time

### ISSUE THREAD

**Issue by cjwyett** [fonsp/Pluto.jl#914]
Hi,

Whenever I have Jupyter and Pluto open at the same time my Jupyter notebook stops connecting to the kernel and my Pluto notebook stops saving. 

My terminal running Jupyter will give me the following error in an endless loop:

```
[ Info: Precompiling IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a]
ERROR: LoadError: ArgumentError: Package MbedTLS_jll does not have JLLWrappers in its dependencies:
- If you have MbedTLS_jll checked out for development and have
  added JLLWrappers as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with MbedTLS_jll
Stacktrace:
 [1] top-level scope at none:2
 [2] eval at ./boot.jl:331 [inlined]
in expression starting at /home/cyrus/Julia/depot/packages/MbedTLS_jll/qMb7d/src/MbedTLS_jll.jl:5
ERROR: LoadError: Failed to precompile MbedTLS_jll [c8ffd9c3-330d-5841-b78e-0817d7145fa1] to /home/cyrus/Julia/depot/compiled/v1.5/MbedTLS_jll/u5NEn_HnYf7.ji.
Stacktrace:
 [1] top-level scope at none:2
 [2] eval at ./boot.jl:331 [inlined]
in expression starting at /home/cyrus/Julia/depot/packages/MbedTLS/4YY6E/src/MbedTLS.jl:3
ERROR: LoadError: LoadError: Failed to precompile MbedTLS [739be429-bea8-5141-9913-cc70e7f3736d] to /home/cyrus/Julia/depot/compiled/v1.5/MbedTLS/bf9T0_HnYf7.ji.
Stacktrace:
 [1] include at ./Base.jl:368 [inlined]
 [2] include(::String) at /home/cyrus/Julia/depot/packages/IJulia/IDNmS/src/IJulia.jl:33
 [3] top-level scope at /home/cyrus/Julia/depot/packages/IJulia/IDNmS/src/IJulia.jl:309
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:331 [inlined]
in expression starting at /home/cyrus/Julia/depot/packages/IJulia/IDNmS/src/hmac.jl:1
in expression starting at /home/cyrus/Julia/depot/packages/IJulia/IDNmS/src/IJulia.jl:309
ERROR: LoadError: Failed to precompile IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a] to /home/cyrus/Julia/depot/compiled/v1.5/IJulia/nfu7T_HnYf7.ji.
in expression starting at /home/cyrus/Julia/depot/packages/IJulia/IDNmS/src/kernel.jl:1
[I 00:13:30.676 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 026b0077-32ca-4294-a030-5724de2685d6 restarted
[E 00:13:30.676 NotebookApp] KernelRestarter: restart callback <bound method ZMQChannelsHandler.on_kernel_restarted of ZMQChannelsHandler(026b0077-32ca-4294-a030-5724de2685d6)> failed
    Traceback (most recent call last):
      File "/home/cyrus/.local/lib/python3.9/site-packages/jupyter_client/restarter.py", line 86, in _fire_callbacks
        callback()
      File "/home/cyrus/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 601, in on_kernel_restarted
        self._send_status_message('restarting')
      File "/home/cyrus/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 597, in _send_status_message
        self.write_message(json.dumps(msg, default=date_default))
      File "/usr/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
        raise WebSocketClosedError()
```

Is this reproducible or is it just me?

**Comment by fonsp** [comment]
If the error happens in Jupyter, then you should report it to https://github.com/JuliaLang/IJulia.jl
